### PR TITLE
Add alt attribute for better SEO

### PR DESCRIPTION
**Pull request by xstable**
This Solves #111

### CODE REVIEW

**Comment by xstable** [comment]
@mariusandra Could you please merge it?

**Comment by mariusandra** [comment]
Hey, merged and thanks for this! I'll release a new patch version as soon as I'm behind my computer (in a few hours)

**Comment by mariusandra** [comment]
Hey, `0.16.1` is out with the fix!

**Comment by xstable** [comment]
Awesome!

**Pull request merged**
