### PR TITLE
Use prop-types

### PR DESCRIPTION
**Pull request by shantp**
PropTypes is deprecated from react 16 so can't use `pigeon-maps` with react 16 without using `prop-types`.

### CODE REVIEW

**Comment by mariusandra** [comment]
Hey, I haven't tested, but are you sure this works?

```js
exports.PropTypes = require('prop-types').PropTypes
```

The `prop-types` package exports the propTypes as `default`, not like this, AFAIK.

Also, I think it makes sense to move `PropTypes` from `infact.js` into `index.js` and just import it normally, as it's in a separate pacakge now that doesn't depend which view layer you're using?

**Comment by shantp** [comment]
I removed PropTypes from infact. I tested react and inferno locally and it's working.

**Comment by mariusandra** [comment]
Thank you!
Could you do one last thing: could you add `prop-types` to peerDependencies in package.json? It could be with just a wildcard (`*`) version.

**Comment by shantp** [comment]
Sure, added it.

**Comment by mariusandra** [comment]
Thanks! I released `v0.8.3` with the patch!

**Comment by shantp** [comment]
Will need to do the same for `pigeon-overlay` and `pigeon-marker`. I can do it later if you don't have time.

**Comment by mariusandra** [comment]
I added `prop-types` and bumped the versions of both of those projects as well.

**Comment by shantp** [comment]
Thanks.

**Pull request merged**
